"""Medial axis of a polygon, computed from bisectors, returned as a graph.

Why Voronoi
-----------
Saidou et al. prove two things (their Lemma 9 and 10): between two boundary
segments that meet at a vertex the skeleton is the *angle bisector*, and
between two parallel segments it is the *median line*. Both are the same
statement, the skeleton is the locus of points equidistant from two pieces of
the boundary.

That locus has a name. Sample the boundary densely and the Voronoi diagram of
those samples is built out of exactly those bisectors: every Voronoi edge is
the perpendicular bisector of a pair of boundary points, and the edges that
fall inside the shape converge to the medial axis as the sampling gets denser
(Brandt & Algazi 1992, Attali & Montanvert 1997).

So this module computes the same object the paper defines, but it finds all the
bisector intersections at once instead of propagating a wavefront. That matters
because the wavefront version needs special handling every time the boundary
turns the wrong way, and medical shapes turn the wrong way constantly. See
bisector.py for what happens when you do it the other way.

The hairs problem
-----------------
The raw Voronoi diagram of boundary samples is not the medial axis, it is the
medial axis plus a hair pointing at every single boundary sample. The classic
fix is the separation angle: at a Voronoi vertex v generated by boundary points
p and q, look at the angle p-v-q. A real medial axis point sees its two closest
boundary points in roughly opposite directions, so the angle is wide. A hair is
generated by two samples sitting next to each other on the boundary, so the
angle is nearly zero. Threshold it and the hairs go away.
"""

import numpy as np
import networkx as nx
from scipy.spatial import Voronoi, cKDTree

from .polygon import (mask_to_polygons, sample_boundary,
                      polygon_contains)


class Skeleton:
    """A skeleton as a graph, not as a picture.

    graph      fine graph, one node per surviving Voronoi vertex
    branches   reduced graph, nodes are only endpoints and junctions, each
               edge carries the polyline of the branch it stands for
    """

    def __init__(self, graph, boundary, meta=None, simplify=0.25):
        self.graph = graph
        self.boundary = boundary
        self.meta = meta or {}
        self.branches = _reduce_to_branches(graph, simplify=simplify)

    # -- geometry ---------------------------------------------------------

    def points(self):
        return np.array([self.graph.nodes[n]["pos"] for n in self.graph])

    def radii(self):
        return np.array([self.graph.nodes[n]["radius"] for n in self.graph])

    def segments(self):
        """Every edge as a pair of endpoints, for plotting."""
        return [(self.graph.nodes[u]["pos"], self.graph.nodes[v]["pos"])
                for u, v in self.graph.edges]

    def polylines(self):
        """One polyline per branch. This is the compact representation."""
        return [d["polyline"] for _, _, d in self.branches.edges(data=True)]

    # -- measurements -----------------------------------------------------

    def total_length(self):
        return float(sum(d["length"] for _, _, d in self.branches.edges(data=True)))

    def n_branches(self):
        return self.branches.number_of_edges()

    def n_endpoints(self):
        return sum(1 for n, d in self.branches.degree() if d == 1)

    def n_bifurcations(self):
        return sum(1 for n, d in self.branches.degree() if d >= 3)

    def n_polyline_vertices(self):
        return int(sum(len(p) for p in self.polylines()))

    def branch_table(self):
        """Per-branch measurements. This is the part a clinician would use."""
        rows = []
        for u, v, d in self.branches.edges(data=True):
            poly = d["polyline"]
            chord = float(np.linalg.norm(poly[-1] - poly[0]))
            rows.append({
                "length": d["length"],
                "chord": chord,
                # tortuosity: how much longer the vessel is than the straight
                # line between its ends. 1.0 is a straight vessel.
                "tortuosity": d["length"] / chord if chord > 1e-9 else np.nan,
                "mean_radius": float(np.mean(d["radii"])),
                "min_radius": float(np.min(d["radii"])),
                "degree_u": self.branches.degree(u),
                "degree_v": self.branches.degree(v),
            })
        return rows

    def __repr__(self):
        return (f"<Skeleton {self.n_branches()} branches, "
                f"{self.n_bifurcations()} bifurcations, "
                f"length={self.total_length():.0f}px>")


def skeletonize(mask, epsilon=2.0, spacing=1.0, theta_deg=70.0,
                prune=1.0, keep_holes=True, largest_component=False):
    """Mask in, skeleton graph out.

    epsilon    RDP tolerance in pixels, the regularization knob
    spacing    boundary sampling step for the Voronoi step
    theta_deg  separation angle threshold, removes the hairs
    prune      remove a leaf branch shorter than prune * (local radius).
               0 disables pruning.

    Every connected component of the mask is skeletonized, not just the
    largest. Both of the defaults here are corrections to earlier versions that
    silently discarded parts of the answer:

    - Only polygonizing the biggest blob looked harmless, since a median 99% of
      a mask survives it. Then on CHASE_DB1 it hit masks whose largest
      component was 52% of the traced vessel and halved the skeleton, while
      pixel thinning kept everything. That is not a defensible comparison.
    - largest_component defaults to False for the same reason one level down:
      the angle test can cut the graph at a tight bifurcation, so even a
      connected mask need not give a connected skeleton, and keeping only the
      biggest piece discarded 22% of total vessel length on the retina image.

    meta["n_components_raw"] records how many pieces the graph came out in,
    because a high count is a warning sign worth seeing.
    """
    boundaries = mask_to_polygons(mask, epsilon=epsilon, keep_holes=keep_holes)

    parts = [skeletonize_polygon(b, spacing=spacing, theta_deg=theta_deg,
                                 prune=prune,
                                 largest_component=largest_component)
             for b in boundaries]
    return _merge(parts, boundaries)


def _merge(parts, boundaries):
    """Combine per-component skeletons into one, renumbering node ids."""
    if len(parts) == 1:
        parts[0].boundaries = boundaries
        return parts[0]

    merged = nx.Graph()
    offset = 0
    meta = {"n_boundary_samples": 0, "n_polygon_vertices": 0,
            "n_voronoi_vertices": 0, "n_components_raw": 0}
    for p in parts:
        merged.add_nodes_from((n + offset, d)
                              for n, d in p.graph.nodes(data=True))
        merged.add_edges_from((u + offset, v + offset, d)
                              for u, v, d in p.graph.edges(data=True))
        offset += max(p.graph.nodes, default=-1) + 1
        for k in meta:
            meta[k] += p.meta.get(k, 0)

    meta["n_mask_components"] = len(parts)
    out = Skeleton(merged, boundaries[0], meta)
    out.boundaries = boundaries
    return out


def skeletonize_polygon(boundary, spacing=1.0, theta_deg=70.0, prune=1.0,
                        largest_component=False):
    samples, _ = sample_boundary(boundary, spacing=spacing)
    if len(samples) < 4:
        raise ValueError("not enough boundary samples for a Voronoi diagram")

    vor = Voronoi(samples)
    verts = vor.vertices

    # separation angle at each Voronoi vertex, see module docstring
    sep = np.zeros(len(verts))
    for (p_id, q_id), (v1, v2) in zip(vor.ridge_points, vor.ridge_vertices):
        if v1 < 0 and v2 < 0:
            continue
        p, q = samples[p_id], samples[q_id]
        for v in (v1, v2):
            if v < 0:
                continue
            a = p - verts[v]
            b = q - verts[v]
            na, nb = np.linalg.norm(a), np.linalg.norm(b)
            if na < 1e-12 or nb < 1e-12:
                continue
            ang = np.degrees(np.arccos(np.clip(a @ b / (na * nb), -1.0, 1.0)))
            if ang > sep[v]:
                sep[v] = ang

    inside = polygon_contains(boundary, verts)
    keep = inside & (sep >= theta_deg)

    tree = cKDTree(samples)
    radius, _ = tree.query(verts)

    g = nx.Graph()
    for v in np.flatnonzero(keep):
        g.add_node(int(v), pos=verts[v], radius=float(radius[v]),
                   sep_angle=float(sep[v]))

    for v1, v2 in vor.ridge_vertices:
        if v1 < 0 or v2 < 0:
            continue
        if keep[v1] and keep[v2]:
            g.add_edge(int(v1), int(v2),
                       length=float(np.linalg.norm(verts[v1] - verts[v2])))

    meta = {"n_boundary_samples": len(samples),
            "n_polygon_vertices": boundary.n_vertices(),
            "n_voronoi_vertices": len(verts),
            "n_components_raw": nx.number_connected_components(g)}

    if largest_component and g.number_of_nodes():
        biggest = max(nx.connected_components(g), key=len)
        g = g.subgraph(biggest).copy()

    if prune > 0 and g.number_of_nodes():
        g = prune_leaves(g, factor=prune)

    return Skeleton(g, boundary, meta)


def prune_leaves(g, factor=1.0, max_rounds=20):
    """Drop leaf branches shorter than `factor` x the radius where they attach.

    Scale adaptive on purpose. A 3 pixel spur hanging off a 40 pixel wide
    ventricle is noise, the same 3 pixel spur on a 2 pixel wide capillary is
    probably a real vessel.
    """
    g = g.copy()
    for _ in range(max_rounds):
        removed = False
        for path, junction in _leaf_paths(g):
            length = sum(g[a][b]["length"] for a, b in zip(path, path[1:]))
            r = g.nodes[junction]["radius"] if junction is not None else 0.0
            if length < factor * r:
                g.remove_nodes_from(path[:-1] if junction is not None else path)
                removed = True
        if not removed:
            break
    return g


def _leaf_paths(g):
    """Walk from every degree-1 node until something that is not degree 2."""
    out = []
    for leaf in [n for n, d in g.degree() if d == 1]:
        if leaf not in g:
            continue
        path = [leaf]
        prev, cur = None, leaf
        while True:
            nbrs = [n for n in g.neighbors(cur) if n != prev]
            if len(nbrs) != 1:
                break
            prev, cur = cur, nbrs[0]
            path.append(cur)
            if g.degree(cur) != 2:
                break
        junction = path[-1] if g.degree(path[-1]) > 2 else None
        out.append((path, junction))
    return out


def _rdp_indices(points, tol):
    """Ramer-Douglas-Peucker, returning kept indices so radii stay aligned.

    The Voronoi vertices along a branch come out spaced far below a pixel, so
    a branch arrives here as a few hundred points describing what is really a
    gentle curve. At a fraction of a pixel of tolerance almost all of them are
    redundant. This is what makes the output smaller than a pixel skeleton
    rather than larger, and it is why the polyline is the honest unit of
    storage rather than the Voronoi vertex.
    """
    n = len(points)
    if n < 3 or tol <= 0:
        return list(range(n))

    keep = np.zeros(n, bool)
    keep[0] = keep[-1] = True
    stack = [(0, n - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1:
            continue
        a, b = points[i], points[j]
        ab = b - a
        L = np.hypot(*ab)
        seg = points[i + 1:j]
        if L < 1e-12:
            d = np.hypot(*(seg - a).T)
        else:
            rel = seg - a
            d = np.abs(ab[0] * rel[:, 1] - ab[1] * rel[:, 0]) / L
        k = int(np.argmax(d))
        if d[k] > tol:
            k += i + 1
            keep[k] = True
            stack.append((i, k))
            stack.append((k, j))
    return list(np.flatnonzero(keep))


def _reduce_to_branches(g, simplify=0.25):
    """Collapse chains of degree-2 nodes into single edges holding a polyline.

    This is where the representation actually gets small: a branch that was 200
    Voronoi vertices becomes one edge with a 200 point polyline attached, and
    everything you want to measure (length, tortuosity, calibre) is a property
    of that edge.
    """
    b = nx.MultiGraph()
    if g.number_of_nodes() == 0:
        return b

    anchors = [n for n, d in g.degree() if d != 2]

    # a pure loop with no junctions has no anchor, break it open at one node
    if not anchors:
        anchors = [next(iter(g.nodes))]

    for n in anchors:
        b.add_node(n, pos=g.nodes[n]["pos"], radius=g.nodes[n]["radius"])

    seen = set()
    for start in anchors:
        for first in g.neighbors(start):
            if (start, first) in seen:
                continue
            path = [start, first]
            seen.add((start, first))
            prev, cur = start, first
            while g.degree(cur) == 2 and cur not in anchors:
                nxt = [n for n in g.neighbors(cur) if n != prev][0]
                seen.add((cur, nxt))
                seen.add((nxt, cur))
                prev, cur = cur, nxt
                path.append(cur)
            seen.add((path[-1], path[-2]))

            end = path[-1]
            if end not in b:
                b.add_node(end, pos=g.nodes[end]["pos"],
                           radius=g.nodes[end]["radius"])

            poly = np.array([g.nodes[n]["pos"] for n in path])
            radii = np.array([g.nodes[n]["radius"] for n in path])

            # length is measured on the full-resolution polyline, before
            # simplification, so the stored geometry getting smaller does not
            # quietly shorten the vessel
            length = float(np.hypot(*np.diff(poly, axis=0).T).sum())

            keep = _rdp_indices(poly, simplify)
            b.add_edge(start, end, polyline=poly[keep], radii=radii[keep],
                       length=length)

    return b
